// <auto-generated />
namespace TestEFCodeFirstRelation.C4Migration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class C41 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(C41));
        
        string IMigrationMetadata.Id
        {
            get { return "201805040635341_C4-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
